name: stellar_dart
description: A comprehensive library for interacting with the Stellar network, including support for operations, smart contracts, and wallet management.
version: 1.5.0
homepage: "https://github.com/mrtnetwork/stellar_dart"
repository: "https://github.com/mrtnetwork/stellar_dart"
Author: mrhaydari.t@gmail.com
topics:
  - stellar
  - contract
  - soroban
  - wallet
  - xlm

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  blockchain_utils: ^4.4.0
  # blockchain_utils:
  #   path: ../blockchain_utils

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.9
  flutter_lints: ^5.0.0
